# Generated by Django 5.2.8 on 2025-12-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Recommendation score (0-1)')),
                ('reasoning', models.TextField(help_text='AI-generated explanation for the recommendation')),
                ('based_on', models.JSONField(default=dict, help_text='Factors used in generating this recommendation')),
                ('term', models.CharField(help_text='Recommended term', max_length=20)),
                ('year', models.IntegerField(help_text='Recommended year')),
                ('is_accepted', models.BooleanField(default=False, help_text='Whether student acted on this recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Recommendation',
                'verbose_name_plural': 'Course Recommendations',
                'db_table': 'course_recommendations',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DegreeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(help_text='Major/program name', max_length=100)),
                ('requirement_type', models.CharField(choices=[('CORE', 'Core Requirement'), ('ELECTIVE', 'Elective'), ('GENERAL_ED', 'General Education'), ('PREREQUISITE', 'Prerequisite')], max_length=50)),
                ('description', models.TextField(help_text='Description of the requirement')),
                ('credits_required', models.IntegerField(default=0, help_text='Number of credits required')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Degree Requirement',
                'verbose_name_plural': 'Degree Requirements',
                'db_table': 'degree_requirements',
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 'Not Helpful'), (2, 'Somewhat Helpful'), (3, 'Helpful'), (4, 'Very Helpful'), (5, 'Extremely Helpful')], null=True)),
                ('comment', models.TextField(blank=True, help_text='User comment about the recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recommendation Feedback',
                'verbose_name_plural': 'Recommendation Feedback',
                'db_table': 'recommendation_feedback',
            },
        ),
    ]
