# Generated by Django 5.2.8 on 2025-12-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_recommendations', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecommendation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courserecommendation',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='degreerequirement',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Specific course if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degree_requirements', to='courses.course'),
        ),
        migrations.AddField(
            model_name='recommendationfeedback',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_recommendations.courserecommendation'),
        ),
        migrations.AddField(
            model_name='recommendationfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to=settings.AUTH_USER_MODEL),
        ),
    ]
