# Generated by Django 5.2.8 on 2025-12-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, help_text='Priority ranking for this course')),
                ('notes', models.TextField(blank=True, help_text='Notes about this course in the plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='courses.coursesection')),
            ],
            options={
                'verbose_name': 'Planned Course',
                'verbose_name_plural': 'Planned Courses',
                'db_table': 'planned_courses',
            },
        ),
        migrations.CreateModel(
            name='StudentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Academic term for this plan', max_length=20)),
                ('year', models.IntegerField(help_text='Academic year for this plan')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('name', models.CharField(help_text='Plan name/description', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Student notes about this plan')),
                ('advisor_comments', models.TextField(blank=True, help_text='Advisor comments on this plan')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_plans', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Plan',
                'verbose_name_plural': 'Student Plans',
                'db_table': 'student_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('TIME_OVERLAP', 'Time Overlap'), ('PREREQUISITE_MISSING', 'Missing Prerequisite')], default='TIME_OVERLAP', max_length=50)),
                ('description', models.TextField(help_text='Description of the conflict')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_first', to='planning.plannedcourse')),
                ('course2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_second', to='planning.plannedcourse')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='planning.studentplan')),
            ],
            options={
                'verbose_name': 'Schedule Conflict',
                'verbose_name_plural': 'Schedule Conflicts',
                'db_table': 'schedule_conflicts',
            },
        ),
        migrations.AddField(
            model_name='plannedcourse',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_courses', to='planning.studentplan'),
        ),
        migrations.AlterUniqueTogether(
            name='plannedcourse',
            unique_together={('plan', 'section')},
        ),
    ]
