# Generated by Django 5.2.8 on 2025-12-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(help_text='Unique course code (e.g., CS101)', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Course title', max_length=200)),
                ('description', models.TextField(help_text='Detailed course description')),
                ('credits', models.IntegerField(default=3, help_text='Number of credit hours')),
                ('department', models.CharField(help_text='Department offering the course', max_length=100)),
                ('level', models.CharField(choices=[('FRESHMAN', 'Freshman'), ('SOPHOMORE', 'Sophomore'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior'), ('GRADUATE', 'Graduate')], default='FRESHMAN', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the course is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Prerequisites for this course', related_name='prerequisite_for', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(help_text='Section number (e.g., 001, A01)', max_length=10)),
                ('term', models.CharField(help_text='Academic term (e.g., Fall 2024, Spring 2025)', max_length=20)),
                ('year', models.IntegerField(help_text='Academic year')),
                ('max_enrollment', models.IntegerField(default=30, help_text='Maximum number of students allowed')),
                ('current_enrollment', models.IntegerField(default=0, help_text='Current number of enrolled students')),
                ('location', models.CharField(blank=True, help_text='Room/building location', max_length=100)),
                ('meeting_days', models.CharField(help_text='Days the class meets (e.g., MWF, TTH)', max_length=50)),
                ('start_time', models.TimeField(help_text='Class start time')),
                ('end_time', models.TimeField(help_text='Class end time')),
                ('is_available', models.BooleanField(default=True, help_text='Whether section is available for registration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Section',
                'verbose_name_plural': 'Course Sections',
                'db_table': 'course_sections',
                'ordering': ['course__course_code', 'section_number'],
                'unique_together': {('course', 'section_number', 'term', 'year')},
            },
        ),
    ]
