# Generated by Django 4.2.27 on 2025-12-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.CharField(
                db_index=True,
                help_text="Department offering the course",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="coursesection",
            name="term",
            field=models.CharField(
                db_index=True,
                help_text="Academic term (e.g., Fall, Spring, Summer)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coursesection",
            name="year",
            field=models.IntegerField(db_index=True, help_text="Academic year"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["department", "level"], name="courses_departm_746cd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursesection",
            index=models.Index(
                fields=["term", "year"], name="course_sect_term_79b01b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursesection",
            index=models.Index(
                fields=["is_available"], name="course_sect_is_avai_712440_idx"
            ),
        ),
    ]
