# Generated by Django 4.2.27 on 2025-12-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_department_alter_coursesection_term_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesection",
            name="attributes",
            field=models.CharField(
                blank=True,
                help_text="Course attributes (e.g., Writing Intensive, Lab)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="coursesection",
            name="campus",
            field=models.CharField(
                blank=True,
                default="Main Campus",
                help_text="Campus location",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="coursesection",
            name="crn",
            field=models.CharField(
                blank=True,
                help_text="Course Reference Number",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="coursesection",
            name="restrictions",
            field=models.TextField(
                blank=True,
                help_text="Registration restrictions (e.g., Major only, Junior standing)",
            ),
        ),
        migrations.AddField(
            model_name="coursesection",
            name="waitlist_capacity",
            field=models.IntegerField(default=10, help_text="Maximum waitlist size"),
        ),
    ]
