# Generated by Django 4.2.27 on 2025-12-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_coursesection_attributes_coursesection_campus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesection",
            name="crn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Course Reference Number",
                max_length=10,
                unique=True,
            ),
        ),
    ]
