# Generated by Django 5.2.8 on 2025-12-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='API endpoint path', max_length=200)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('status_code', models.IntegerField(help_text='HTTP status code')),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Metric',
                'verbose_name_plural': 'API Metrics',
                'db_table': 'api_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='api_metrics_timesta_bdc411_idx'), models.Index(fields=['endpoint'], name='api_metrics_endpoin_a7afa2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('module', models.CharField(help_text='Module or component that generated the log', max_length=100)),
                ('message', models.TextField(help_text='Log message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context and metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'db_table': 'system_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='system_logs_timesta_789991_idx'), models.Index(fields=['level'], name='system_logs_level_245244_idx'), models.Index(fields=['module'], name='system_logs_module_ac9b9d_idx')],
            },
        ),
    ]
