# Generated by Django 5.2.8 on 2025-12-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisor', '0001_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorassignment',
            name='advisor',
            field=models.ForeignKey(limit_choices_to={'role': 'ADVISOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advisorassignment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Related student plan if message is about a specific plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='planning.studentplan'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plancomment',
            name='advisor',
            field=models.ForeignKey(limit_choices_to={'role': 'ADVISOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='plan_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plancomment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='planning.studentplan'),
        ),
        migrations.AlterUniqueTogether(
            name='advisorassignment',
            unique_together={('student', 'advisor', 'is_active')},
        ),
    ]
