# Generated by Django 5.2.8 on 2025-12-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REGISTRATION_DEADLINE', 'Registration Deadline'), ('MEETING_REMINDER', 'Meeting Reminder'), ('SCHEDULE_CHANGE', 'Schedule Change'), ('ADVISOR_ACTION', 'Advisor Action'), ('PLAN_APPROVED', 'Plan Approved'), ('PLAN_REJECTED', 'Plan Rejected'), ('NEW_MESSAGE', 'New Message'), ('ENROLLMENT_CONFIRMED', 'Enrollment Confirmed'), ('WAITLIST_UPDATE', 'Waitlist Update'), ('GENERAL', 'General')], max_length=30)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('link', models.URLField(blank=True, help_text='Link to relevant page')),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False, help_text='Whether notification has been delivered')),
                ('send_email', models.BooleanField(default=False, help_text='Whether to send email notification')),
                ('email_sent', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive notifications via email')),
                ('push_notifications', models.BooleanField(default=True, help_text='Receive push notifications')),
                ('registration_deadlines', models.BooleanField(default=True)),
                ('meeting_reminders', models.BooleanField(default=True)),
                ('schedule_changes', models.BooleanField(default=True)),
                ('advisor_actions', models.BooleanField(default=True)),
                ('new_messages', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
    ]
